Traceback (most recent call last):
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/jupyter_cache-0.4.1-py3.7.egg/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mayhew/anaconda3/envs/jb08/lib/python3.7/site-packages/nbclient-0.5.1-py3.7.egg/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
##Plot of a Gaussian (hide input)
import numpy as np
import matplotlib.pyplot as plt

mu = 0
sigma = 1
x = np.linspace(-2.5*sigma, 2.5*sigma, 1000)
xticks = [0]
xlabels = [r'$\mu$']
fs = 16

def gauss(x, mean, std_dev):
    return 1/std_dev/np.sqrt(2*np.pi) * np.exp(-0.5*(x - mean)**2/std_dev/std_dev)

fig, ax = plt.subplots()

ax.plot(x, gauss(x, mu, sigma), color = 'black', linewidth = 2)


ax.set_ylim([0, 1.05*gauss(mu, mu, sigma)])

ax.set_xticks(xticks)
ax.set_xticklabels(xlabels, fontsize = fs)
ax.set_yticks([])

ax.set_xlabel('x', fontsize = fs)
ax.set_ylabel('p(x)', fontsize = fs)

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-966caa99400a>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m##Plot of a Gaussian (hide input)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mmu[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

